apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-i43z
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkrw-pr712-0075-0066-tenant/tkrw-pr712-0075-0066-app/devfile-sample-i43z@sha256:0a3d8f284275e6b39f609dfac306d1a0df9bbf81a3ee4f91a723f1c692373cb6
        name: my-nodejs
        resources: {}
status: {}
